/** Compact content packs for 10 Superdewa hubs */

export const GROUP_URLS = [
  "https://superdewa-slot.com/",
  "https://superdewa-pg.com/",
  "https://superdewa-pp.com/",
  "https://superdewa-habanero.com/",
  "https://superdewa-microgaming.com/",
  "https://superdewa-nolimit.com/",
  "https://superdewa-live.com/",
  "https://superdewa-crash.com/",
  "https://superdewa-sports.com/",
  "https://superdewa-play.com/",
];

/** [slug, shortLabel, keyword] */
export const sites = [
  {
    id: "slot",
    domain: "superdewa-slot.com",
    accent: "site-accent-bolt",
    hero: "slot.svg",
    topic: "slot",
    name: "Slot Glosarium & How to Play",
    nav: "Slot Guide",
    pillarTitle: "Slot 101 Superdewa — Glosarium & Cara Main Biar Gak Bingung",
    pillarH1: "Slot 101: istilah wajib + cara main yang beneran masuk akal",
    pillarDek: "Dari RTP sampe scatter, kita breakdown santai tapi jelas. Cocok buat yang baru start atau yang pengen refresh ilmu biar mainnya lebih chill.",
    keyword: "cara main slot, istilah slot",
    about: "Hub edukasi slot Superdewa: glosarium, mekanik, dan tips main bijak tanpa klaim palsu.",
    glossaries: [
      ["rtp", "RTP", "arti RTP slot"],
      ["volatilitas", "Volatilitas", "volatilitas slot"],
      ["payline", "Payline", "payline slot"],
      ["paytable", "Paytable", "paytable slot"],
      ["scatter", "Scatter", "arti scatter slot"],
      ["wild", "Wild", "arti wild slot"],
      ["expanding-wild", "Expanding Wild", "expanding wild"],
      ["sticky-wild", "Sticky Wild", "sticky wild"],
      ["free-spin", "Free Spin", "free spin artinya"],
      ["multiplier", "Multiplier", "multiplier slot"],
      ["buy-feature", "Buy Feature", "buy feature slot"],
      ["megaways", "Megaways", "megaways artinya"],
      ["cascading-reels", "Cascading Reels", "cascading reels"],
      ["progressive-jackpot", "Progressive Jackpot", "progressive jackpot"],
      ["hit-frequency", "Hit Frequency", "hit frequency slot"],
      ["max-win", "Max Win", "max win slot"],
      ["bet-level", "Bet Level", "bet level slot"],
      ["autoplay", "Autoplay", "autoplay slot"],
      ["demo-mode", "Demo Mode", "demo mode slot"],
      ["rng", "RNG", "RNG slot artinya"],
    ],
    guides: [
      ["cara-main-slot-pemula", "Cara Main Slot Pemula", "cara main slot pemula"],
      ["cara-baca-rtp", "Cara Baca RTP", "cara baca RTP"],
      ["cara-pilih-volatilitas", "Cara Pilih Volatilitas", "cara pilih volatilitas"],
      ["cara-atur-bet", "Cara Atur Bet", "cara atur bet slot"],
      ["cara-pakai-autoplay", "Cara Pakai Autoplay", "cara pakai autoplay"],
      ["cara-baca-paytable", "Cara Baca Paytable", "cara baca paytable"],
      ["cara-main-free-spin", "Cara Main Free Spin", "cara main free spin"],
      ["cara-pahami-buy-feature", "Cara Pahami Buy Feature", "cara buy feature"],
      ["demo-vs-real", "Demo vs Real", "demo vs real slot"],
      ["manajemen-bankroll-slot", "Manajemen Bankroll Slot", "manajemen bankroll slot"],
      ["mitos-pola-gacor", "Mitos Pola Gacor", "mitos pola gacor"],
      ["cara-main-mobile", "Cara Main di Mobile", "cara main slot mobile"],
      ["checklist-sebelum-spin", "Checklist Sebelum Spin", "checklist main slot"],
      ["cara-hindari-tilt", "Cara Hindari Tilt", "cara menghindari tilt"],
    ],
    games: [
      ["slot-klasik-3-reel", "Slot Klasik 3 Reel", "slot klasik 3 reel"],
      ["slot-video", "Slot Video", "slot video"],
      ["megaways-games", "Game Megaways", "game megaways"],
      ["hold-and-win", "Hold and Win", "hold and win"],
      ["cluster-pays", "Cluster Pays", "cluster pays"],
      ["cascading-games", "Cascading Games", "cascading slot"],
      ["progressive-games", "Progressive Games", "progressive jackpot games"],
      ["branded-theme", "Branded Theme", "branded slot"],
      ["high-volatility", "High Volatility", "slot volatilitas tinggi"],
      ["low-volatility", "Low Volatility", "slot volatilitas rendah"],
      ["buy-bonus-games", "Buy Bonus Games", "slot buy bonus"],
      ["jackpot-lokal-vs-network", "Jackpot Lokal vs Network", "jackpot lokal vs network"],
    ],
    tips: [
      ["session-timer", "Session Timer", "tips timer main slot"],
      ["stop-loss-sederhana", "Stop Loss Sederhana", "stop loss slot"],
      ["catat-hasil-main", "Catat Hasil Main", "catat hasil main slot"],
      ["main-pas-fresh", "Main Saat Fresh", "tips main slot"],
      ["jangan-kejar-rugi", "Jangan Kejar Rugi", "jangan kejar kerugian"],
      ["pilih-game-sesuai-mood", "Pilih Game Sesuai Mood", "pilih game slot"],
    ],
  },
  {
    id: "pg",
    domain: "superdewa-pg.com",
    accent: "site-accent-cyan",
    hero: "pg.svg",
    topic: "PG Soft",
    name: "PG Soft Games Guide",
    nav: "PG Soft",
    pillarTitle: "Panduan PG Soft Superdewa — Cascading & Multiplier Trail",
    pillarH1: "PG Soft guide: cascading biar makin paham, bukan cuma spam spin",
    pillarDek: "Mahjong Ways sampe Wild Bandito — kita bahas mekanik khas PG Soft dengan bahasa yang enak dicerna.",
    keyword: "panduan PG Soft, game PG Soft",
    about: "Panduan edukasi game PG Soft dari Superdewa: fitur, ritme, dan tips session sehat.",
    glossaries: [
      ["cascading-wins", "Cascading Wins", "cascading wins PG Soft"],
      ["multiplier-trail", "Multiplier Trail", "multiplier trail PG Soft"],
      ["win-both-ways", "Win Both Ways", "win both ways"],
      ["tumble-pg", "Tumble PG Soft", "tumble PG Soft"],
      ["free-spins-pg", "Free Spins PG Soft", "free spins PG Soft"],
      ["wild-multiplier", "Wild Multiplier", "wild multiplier PG"],
      ["symbol-upgrade", "Symbol Upgrade", "symbol upgrade PG Soft"],
      ["energy-meter", "Energy Meter", "energy meter PG Soft"],
      ["feature-spin", "Feature Spin", "feature spin PG Soft"],
      ["max-multiplier", "Max Multiplier", "max multiplier PG Soft"],
      ["ways-to-win", "Ways to Win", "ways to win PG Soft"],
      ["scatter-pay", "Scatter Pay", "scatter pay PG Soft"],
      ["volatility-pg", "Volatilitas PG Soft", "volatilitas PG Soft"],
      ["rtp-pg", "RTP PG Soft", "RTP PG Soft"],
      ["mobile-portrait", "Mobile Portrait", "PG Soft portrait mode"],
      ["ante-bet-pg", "Ante Bet PG", "ante bet PG Soft"],
      ["super-free-spins", "Super Free Spins", "super free spins PG"],
      ["golden-symbol", "Golden Symbol", "golden symbol PG Soft"],
      ["stack-symbol", "Stack Symbol", "stack symbol PG Soft"],
      ["pg-ui", "UI PG Soft", "antarmuka PG Soft"],
    ],
    guides: [
      ["cara-main-pg-soft", "Cara Main PG Soft", "cara main PG Soft"],
      ["cara-baca-multiplier-trail", "Cara Baca Multiplier Trail", "cara baca multiplier trail"],
      ["cara-main-mahjong-ways", "Cara Main Mahjong Ways", "cara main Mahjong Ways"],
      ["cara-main-lucky-neko", "Cara Main Lucky Neko", "cara main Lucky Neko"],
      ["cara-main-wild-bandito", "Cara Main Wild Bandito", "cara main Wild Bandito"],
      ["cara-main-treasures-of-aztec", "Cara Main Treasures of Aztec", "cara main Treasures of Aztec"],
      ["tips-volatilitas-pg", "Tips Volatilitas PG", "tips volatilitas PG Soft"],
      ["manajemen-bet-pg", "Manajemen Bet PG Soft", "manajemen bet PG Soft"],
      ["portrait-mode-tips", "Portrait Mode Tips", "tips portrait PG Soft"],
      ["fitur-feature-buy-pg", "Feature Buy PG Soft", "feature buy PG Soft"],
      ["demo-pg", "Demo PG Soft", "demo PG Soft"],
      ["pola-session-pendek", "Session Pendek PG Soft", "session pendek PG Soft"],
      ["bandingkan-pg-vs-pp", "PG Soft vs Pragmatic", "PG Soft vs Pragmatic Play"],
      ["checklist-pg-pemula", "Checklist PG Soft Pemula", "checklist PG Soft pemula"],
    ],
    games: [
      ["mahjong-ways", "Mahjong Ways", "Mahjong Ways"],
      ["mahjong-ways-2", "Mahjong Ways 2", "Mahjong Ways 2"],
      ["lucky-neko", "Lucky Neko", "Lucky Neko"],
      ["treasures-of-aztec", "Treasures of Aztec", "Treasures of Aztec"],
      ["wild-bandito", "Wild Bandito", "Wild Bandito"],
      ["fortune-ox", "Fortune Ox", "Fortune Ox"],
      ["fortune-tiger", "Fortune Tiger", "Fortune Tiger"],
      ["fortune-rabbit", "Fortune Rabbit", "Fortune Rabbit"],
      ["garuda-gems", "Garuda Gems", "Garuda Gems"],
      ["butterfly-blossom", "Butterfly Blossom", "Butterfly Blossom"],
      ["jungle-delight", "Jungle Delight", "Jungle Delight"],
      ["double-fortune", "Double Fortune", "Double Fortune"],
    ],
    tips: [
      ["main-portrait-nyaman", "Main Portrait Nyaman", "tips portrait PG Soft"],
      ["pantau-multiplier", "Pantau Multiplier", "tips multiplier PG Soft"],
      ["jangan-spam-feature-buy", "Jangan Spam Feature Buy", "tips feature buy PG"],
      ["cooldown-antar-session", "Cooldown Antar Session", "cooldown main PG Soft"],
      ["pilih-tema-favorite", "Pilih Tema Favorit", "pilih game PG Soft"],
      ["catat-max-win-info", "Catat Max Win Info", "max win PG Soft"],
    ],
  },
  {
    id: "pp",
    domain: "superdewa-pp.com",
    accent: "site-accent-red",
    hero: "pp.svg",
    topic: "Pragmatic Play",
    name: "Pragmatic Play Games Guide",
    nav: "Pragmatic",
    pillarTitle: "Panduan Pragmatic Play Superdewa — Tumble, Multiplier & Free Spin",
    pillarH1: "Pragmatic Play 101: tumble, multiplier, dan free spin tanpa drama",
    pillarDek: "Gates, Sweet Bonanza, Starlight — kita kupas mekanik PP biar kamu main dengan kepala dingin.",
    keyword: "panduan Pragmatic Play",
    about: "Panduan edukasi Pragmatic Play Superdewa fokus mekanik, risiko, dan ekspektasi realistis.",
    glossaries: [
      ["tumble", "Tumble", "tumble Pragmatic Play"],
      ["multiplier-symbol", "Multiplier Symbol", "multiplier symbol Pragmatic"],
      ["ante-bet", "Ante Bet", "ante bet Pragmatic"],
      ["bonus-buy", "Bonus Buy", "bonus buy Pragmatic"],
      ["free-spins-pp", "Free Spins PP", "free spins Pragmatic Play"],
      ["scatter-pp", "Scatter PP", "scatter Pragmatic Play"],
      ["wild-pp", "Wild PP", "wild Pragmatic Play"],
      ["pay-anywhere", "Pay Anywhere", "pay anywhere Pragmatic"],
      ["cluster-pp", "Cluster PP", "cluster Pragmatic Play"],
      ["high-volatility-pp", "High Volatility PP", "volatilitas tinggi Pragmatic"],
      ["rtp-range", "RTP Range", "RTP Pragmatic Play"],
      ["max-win-pp", "Max Win PP", "max win Pragmatic"],
      ["random-multiplier", "Random Multiplier", "random multiplier Pragmatic"],
      ["growing-multiplier", "Growing Multiplier", "growing multiplier Pragmatic"],
      ["respins-pp", "Respins PP", "respins Pragmatic"],
      ["hold-and-win-pp", "Hold and Win PP", "hold and win Pragmatic"],
      ["megaways-pp", "Megaways PP", "Megaways Pragmatic"],
      ["live-side", "Live Side PP", "Pragmatic Live"],
      ["demo-pp", "Demo PP", "demo Pragmatic Play"],
      ["volatility-index", "Volatility Index", "volatility index Pragmatic"],
    ],
    guides: [
      ["cara-main-pragmatic", "Cara Main Pragmatic Play", "cara main Pragmatic Play"],
      ["cara-main-gates-of-olympus", "Cara Main Gates of Olympus", "cara main Gates of Olympus"],
      ["cara-main-sweet-bonanza", "Cara Main Sweet Bonanza", "cara main Sweet Bonanza"],
      ["cara-main-starlight-princess", "Cara Main Starlight Princess", "cara main Starlight Princess"],
      ["cara-main-sugar-rush", "Cara Main Sugar Rush", "cara main Sugar Rush"],
      ["paham-ante-bet", "Pahami Ante Bet", "cara pakai ante bet"],
      ["paham-bonus-buy", "Pahami Bonus Buy", "cara bonus buy Pragmatic"],
      ["baca-max-win", "Cara Baca Max Win", "cara baca max win Pragmatic"],
      ["session-high-vol", "Session High Volatility", "session volatilitas tinggi"],
      ["bankroll-pp", "Bankroll Pragmatic Play", "bankroll Pragmatic Play"],
      ["mitos-jam-gacor", "Mitos Jam Gacor", "mitos jam gacor Pragmatic"],
      ["mobile-pp", "Main PP di Mobile", "Pragmatic Play mobile"],
      ["bandingkan-tumble-vs-payline", "Tumble vs Payline", "tumble vs payline"],
      ["checklist-pp", "Checklist Pragmatic Pemula", "checklist Pragmatic Play"],
    ],
    games: [
      ["gates-of-olympus", "Gates of Olympus", "Gates of Olympus"],
      ["sweet-bonanza", "Sweet Bonanza", "Sweet Bonanza"],
      ["starlight-princess", "Starlight Princess", "Starlight Princess"],
      ["sugar-rush", "Sugar Rush", "Sugar Rush"],
      ["fruit-party", "Fruit Party", "Fruit Party"],
      ["the-dog-house", "The Dog House", "The Dog House"],
      ["big-bass-bonanza", "Big Bass Bonanza", "Big Bass Bonanza"],
      ["wild-west-gold", "Wild West Gold", "Wild West Gold"],
      ["john-holt", "John Hunter Titles", "John Hunter Pragmatic"],
      ["madame-destiny", "Madame Destiny", "Madame Destiny"],
      ["floating-dragon", "Floating Dragon", "Floating Dragon"],
      ["release-the-kraken", "Release the Kraken", "Release the Kraken"],
    ],
    tips: [
      ["mulai-bet-kecil", "Mulai Bet Kecil", "tips bet Pragmatic"],
      ["kenali-vol-dulu", "Kenali Volatilitas Dulu", "tips volatilitas Pragmatic"],
      ["jangan-kejar-multiplier", "Jangan Kejar Multiplier", "tips multiplier Pragmatic"],
      ["set-limit-harian", "Set Limit Harian", "limit harian main slot"],
      ["istirahat-setelah-bonus", "Istirahat Setelah Bonus", "tips setelah free spin"],
      ["baca-aturan-pay", "Baca Aturan Pay", "tips baca paytable Pragmatic"],
    ],
  },
  {
    id: "habanero",
    domain: "superdewa-habanero.com",
    accent: "site-accent-amber",
    hero: "habanero.svg",
    topic: "Habanero",
    name: "Habanero Games Guide",
    nav: "Habanero",
    pillarTitle: "Panduan Habanero Superdewa — Klasik, Feature-Rich, Vibe Arcade",
    pillarH1: "Habanero guide: klasik, feature-rich, tetap enak buat dipelajari",
    pillarDek: "Dari Koi Gate sampe Hot Hot Fruit — kupas fitur Habanero biar mainnya lebih sadar mekanik.",
    keyword: "panduan Habanero",
    about: "Panduan edukasi slot Habanero Superdewa: fitur, ritme klasik, dan tips bijak.",
    glossaries: [
      ["free-spins-habanero", "Free Spins Habanero", "free spins Habanero"],
      ["wild-habanero", "Wild Habanero", "wild Habanero"],
      ["scatter-habanero", "Scatter Habanero", "scatter Habanero"],
      ["stacked-symbols", "Stacked Symbols", "stacked symbols Habanero"],
      ["expanding-symbols", "Expanding Symbols", "expanding symbols Habanero"],
      ["gamble-feature", "Gamble Feature", "gamble feature Habanero"],
      ["bonus-game", "Bonus Game", "bonus game Habanero"],
      ["progressive-habanero", "Progressive Habanero", "progressive Habanero"],
      ["rtp-habanero", "RTP Habanero", "RTP Habanero"],
      ["volatility-habanero", "Volatilitas Habanero", "volatilitas Habanero"],
      ["ways-to-win-hab", "Ways to Win", "ways to win Habanero"],
      ["pick-bonus", "Pick Bonus", "pick bonus Habanero"],
      ["respins-hab", "Respins Habanero", "respins Habanero"],
      ["cascading-hab", "Cascading Habanero", "cascading Habanero"],
      ["coin-feature", "Coin Feature", "coin feature Habanero"],
      ["jackpot-card", "Jackpot Card", "jackpot card Habanero"],
      ["mobile-hab", "Mobile Habanero", "Habanero mobile"],
      ["demo-hab", "Demo Habanero", "demo Habanero"],
      ["max-win-hab", "Max Win Habanero", "max win Habanero"],
      ["feature-trigger", "Feature Trigger", "feature trigger Habanero"],
    ],
    guides: [
      ["cara-main-habanero", "Cara Main Habanero", "cara main Habanero"],
      ["cara-main-koi-gate", "Cara Main Koi Gate", "cara main Koi Gate"],
      ["cara-main-hot-hot-fruit", "Cara Main Hot Hot Fruit", "cara main Hot Hot Fruit"],
      ["cara-main-fa-cai-shen", "Cara Main Fa Cai Shen", "cara main Fa Cai Shen"],
      ["paham-gamble-feature", "Pahami Gamble Feature", "cara gamble feature"],
      ["tips-stacked-wild", "Tips Stacked Wild", "tips stacked wild Habanero"],
      ["manajemen-bet-hab", "Manajemen Bet Habanero", "manajemen bet Habanero"],
      ["klasik-vs-modern-hab", "Klasik vs Modern Habanero", "slot klasik vs modern Habanero"],
      ["session-pendek-hab", "Session Pendek Habanero", "session pendek Habanero"],
      ["demo-habanero", "Demo Habanero Dulu", "demo Habanero dulu"],
      ["baca-paytable-hab", "Baca Paytable Habanero", "cara baca paytable Habanero"],
      ["mobile-tips-hab", "Tips Mobile Habanero", "tips mobile Habanero"],
      ["bandingkan-hab-vs-pg", "Habanero vs PG Soft", "Habanero vs PG Soft"],
      ["checklist-hab", "Checklist Habanero Pemula", "checklist Habanero"],
    ],
    games: [
      ["koi-gate", "Koi Gate", "Koi Gate"],
      ["hot-hot-fruit", "Hot Hot Fruit", "Hot Hot Fruit"],
      ["fa-cai-shen", "Fa Cai Shen", "Fa Cai Shen"],
      ["fa-cai-shen-2", "Fa Cai Shen 2", "Fa Cai Shen 2"],
      ["throne-of-egypt", "Throne of Egypt", "Throne of Egypt"],
      ["wicked-witch", "Wicked Witch", "Wicked Witch"],
      ["mystic-fortune", "Mystic Fortune", "Mystic Fortune"],
      ["hawaiian-fantasy", "Hawaiian Fantasy", "Hawaiian Fantasy"],
      ["carnival-cash", "Carnival Cash", "Carnival Cash"],
      ["dragon-king", "Dragon King", "Dragon King"],
      ["scopa", "Scopa", "Scopa Habanero"],
      ["all-for-one", "All for One", "All for One Habanero"],
    ],
    tips: [
      ["uji-demo-dulu", "Uji Demo Dulu", "tips demo Habanero"],
      ["hati-hati-gamble", "Hati-hati Gamble Feature", "tips gamble feature"],
      ["pilih-tema-santai", "Pilih Tema Santai", "tips pilih game Habanero"],
      ["limit-session-hab", "Limit Session", "limit session Habanero"],
      ["catat-fitur-favorit", "Catat Fitur Favorit", "fitur favorit Habanero"],
      ["jangan-spam-spin", "Jangan Spam Spin", "tips jangan spam spin"],
    ],
  },
  {
    id: "microgaming",
    domain: "superdewa-microgaming.com",
    accent: "site-accent-teal",
    hero: "microgaming.svg",
    topic: "Microgaming",
    name: "Microgaming Games Guide",
    nav: "Microgaming",
    pillarTitle: "Panduan Microgaming Superdewa — Jackpot Network & Klasik Legend",
    pillarH1: "Microgaming guide: jackpot network & klasik legend, ekspektasi tetap realistis",
    pillarDek: "Mega Moolah sampe Immortal Romance — kita bahas mekanik dan mindset biar gak kejebak fantasi jackpot.",
    keyword: "panduan Microgaming",
    about: "Panduan edukasi Microgaming Superdewa: jackpot, klasik, dan kontrol diri.",
    glossaries: [
      ["progressive-network", "Progressive Network", "progressive network Microgaming"],
      ["mega-moolah", "Mega Moolah", "Mega Moolah artinya"],
      ["daily-jackpot", "Daily Jackpot", "daily jackpot Microgaming"],
      ["must-drop", "Must Drop", "must drop jackpot"],
      ["free-spins-mg", "Free Spins MG", "free spins Microgaming"],
      ["wild-mg", "Wild MG", "wild Microgaming"],
      ["scatter-mg", "Scatter MG", "scatter Microgaming"],
      ["bonus-round", "Bonus Round", "bonus round Microgaming"],
      ["rtp-mg", "RTP Microgaming", "RTP Microgaming"],
      ["volatility-mg", "Volatilitas MG", "volatilitas Microgaming"],
      ["ways-to-win-mg", "Ways to Win MG", "ways to win Microgaming"],
      ["cascading-mg", "Cascading MG", "cascading Microgaming"],
      ["branded-slots", "Branded Slots", "branded slots Microgaming"],
      ["jackpot-pool", "Jackpot Pool", "jackpot pool Microgaming"],
      ["contribution-rate", "Contribution Rate", "contribution rate jackpot"],
      ["mobile-mg", "Mobile Microgaming", "Microgaming mobile"],
      ["demo-mg", "Demo Microgaming", "demo Microgaming"],
      ["max-win-mg", "Max Win MG", "max win Microgaming"],
      ["feature-trigger-mg", "Feature Trigger MG", "feature trigger Microgaming"],
      ["legend-titles", "Legend Titles", "slot klasik Microgaming"],
    ],
    guides: [
      ["cara-main-microgaming", "Cara Main Microgaming", "cara main Microgaming"],
      ["paham-progressive-jackpot", "Pahami Progressive Jackpot", "cara kerja progressive jackpot"],
      ["cara-main-mega-moolah", "Cara Main Mega Moolah", "cara main Mega Moolah"],
      ["cara-main-immortal-romance", "Cara Main Immortal Romance", "cara main Immortal Romance"],
      ["tips-jackpot-game", "Tips Main Jackpot Game", "tips main jackpot"],
      ["bankroll-jackpot", "Bankroll untuk Jackpot", "bankroll jackpot"],
      ["ekspektasi-realistis", "Ekspektasi Realistis Jackpot", "ekspektasi jackpot realistis"],
      ["demo-mg-guide", "Demo Microgaming", "demo Microgaming dulu"],
      ["baca-rtp-mg", "Cara Baca RTP MG", "cara baca RTP Microgaming"],
      ["session-disiplin", "Session Disiplin", "session disiplin jackpot"],
      ["mobile-mg-guide", "Mobile Microgaming Tips", "tips mobile Microgaming"],
      ["bandingkan-mg-vs-pp", "Microgaming vs Pragmatic", "Microgaming vs Pragmatic"],
      ["mitos-jackpot", "Mitos Jackpot", "mitos jackpot slot"],
      ["checklist-mg", "Checklist Microgaming", "checklist Microgaming"],
    ],
    games: [
      ["mega-moolah-game", "Mega Moolah", "Mega Moolah"],
      ["immortal-romance", "Immortal Romance", "Immortal Romance"],
      ["thunderstruck-ii", "Thunderstruck II", "Thunderstruck II"],
      ["break-da-bank-again", "Break Da Bank Again", "Break Da Bank Again"],
      ["agent-jane-blonde", "Agent Jane Blonde", "Agent Jane Blonde"],
      ["game-of-thrones", "Game of Thrones Slot", "Game of Thrones Microgaming"],
      ["playboy", "Playboy Slot", "Playboy Microgaming"],
      ["cascading-reels-classic", "Cascading Reels Classic", "Cascading Reels Microgaming"],
      ["pure-platinum", "Pure Platinum", "Pure Platinum"],
      ["lucky-twins", "Lucky Twins", "Lucky Twins"],
      ["egyptian-myths", "Egyptian Myths", "Egyptian Myths"],
      ["high-society", "High Society", "High Society Microgaming"],
    ],
    tips: [
      ["jackpot-bukan-atm", "Jackpot Bukan ATM", "tips jackpot realistis"],
      ["set-budget-khusus", "Set Budget Khusus", "budget khusus jackpot"],
      ["main-hiburan", "Main untuk Hiburan", "main jackpot hiburan"],
      ["jangan-all-in", "Jangan All-in", "jangan all in jackpot"],
      ["cooldown-panjang", "Cooldown Panjang", "cooldown setelah main jackpot"],
      ["prioritaskan-game-paham", "Prioritaskan Game yang Dipahami", "pilih game Microgaming"],
    ],
  },
  {
    id: "nolimit",
    domain: "superdewa-nolimit.com",
    accent: "site-accent-pink",
    hero: "nolimit.svg",
    topic: "Nolimit City",
    name: "Nolimit City Games Guide",
    nav: "Nolimit",
    pillarTitle: "Panduan Nolimit City Superdewa — xNudge, xWays, xBet Decoded",
    pillarH1: "Nolimit City decoded: xNudge, xWays, xBet biar gak bingung",
    pillarDek: "Extreme volatility, mekanik unik, vibe liar. Kita translate ke bahasa manusia biar kamu sadar risiko.",
    keyword: "panduan Nolimit City",
    about: "Panduan edukasi Nolimit City Superdewa: mekanik x-series dan kontrol risiko ekstrem.",
    glossaries: [
      ["xnudge", "xNudge", "xNudge artinya"],
      ["xways", "xWays", "xWays artinya"],
      ["xbet", "xBet", "xBet artinya"],
      ["xbomb", "xBomb", "xBomb artinya"],
      ["xsplit", "xSplit", "xSplit artinya"],
      ["xmanteia", "xManteia", "xManteia artinya"],
      ["volatility-extreme", "Volatility Extreme", "volatilitas ekstrem Nolimit"],
      ["rtp-nolimit", "RTP Nolimit", "RTP Nolimit City"],
      ["free-spins-nlc", "Free Spins NLC", "free spins Nolimit City"],
      ["wild-nlc", "Wild NLC", "wild Nolimit City"],
      ["multiplier-nlc", "Multiplier NLC", "multiplier Nolimit City"],
      ["bonus-buy-nlc", "Bonus Buy NLC", "bonus buy Nolimit City"],
      ["max-win-nlc", "Max Win NLC", "max win Nolimit City"],
      ["horror-theme", "Horror Theme", "slot horror Nolimit"],
      ["feature-drop", "Feature Drop", "feature drop Nolimit"],
      ["mobile-nlc", "Mobile NLC", "Nolimit City mobile"],
      ["demo-nlc", "Demo NLC", "demo Nolimit City"],
      ["high-risk", "High Risk Play", "high risk Nolimit City"],
      ["symbol-transform", "Symbol Transform", "symbol transform Nolimit"],
      ["consecutive-wins", "Consecutive Wins", "consecutive wins Nolimit"],
    ],
    guides: [
      ["cara-main-nolimit-city", "Cara Main Nolimit City", "cara main Nolimit City"],
      ["paham-xnudge", "Pahami xNudge", "cara kerja xNudge"],
      ["paham-xways", "Pahami xWays", "cara kerja xWays"],
      ["paham-xbet", "Pahami xBet", "cara kerja xBet"],
      ["cara-main-mental", "Cara Main Mental", "cara main Mental Nolimit"],
      ["cara-main-tombstone", "Cara Main Tombstone", "cara main Tombstone"],
      ["cara-main-fire-in-the-hole", "Cara Main Fire in the Hole", "cara main Fire in the Hole"],
      ["tips-extreme-volatility", "Tips Extreme Volatility", "tips volatilitas ekstrem"],
      ["bankroll-nlc", "Bankroll Nolimit City", "bankroll Nolimit City"],
      ["demo-wajib", "Demo Wajib Nolimit", "demo wajib Nolimit City"],
      ["session-micro", "Session Micro Nolimit", "session pendek Nolimit"],
      ["baca-max-win-nlc", "Baca Max Win NLC", "cara baca max win Nolimit"],
      ["bandingkan-nlc-vs-pp", "Nolimit vs Pragmatic", "Nolimit City vs Pragmatic"],
      ["checklist-nlc", "Checklist Nolimit Pemula", "checklist Nolimit City"],
    ],
    games: [
      ["mental", "Mental", "Mental Nolimit City"],
      ["tombstone", "Tombstone", "Tombstone Nolimit"],
      ["fire-in-the-hole", "Fire in the Hole", "Fire in the Hole"],
      ["san-quentin", "San Quentin", "San Quentin Nolimit"],
      ["road-rage", "Road Rage", "Road Rage Nolimit"],
      ["bunko-squad", "Bushido / Bunko Vibes", "Bunko Squad Nolimit"],
      ["toxic", "Toxic Series", "Toxic Nolimit City"],
      ["bushido", "Bushido", "Bushido Nolimit"],
      ["blood-and-shadow", "Blood & Shadow", "Blood and Shadow"],
      ["true-grit", "True Grit", "True Grit Nolimit"],
      ["serial", "Serial", "Serial Nolimit City"],
      ["disturbed", "Disturbed", "Disturbed Nolimit"],
    ],
    tips: [
      ["hanya-bet-yang-rela-hilang", "Hanya Bet yang Rela Hilang", "tips bet Nolimit City"],
      ["demo-panjang", "Demo Panjang", "tips demo Nolimit"],
      ["stop-loss-ketat", "Stop Loss Ketat", "stop loss Nolimit City"],
      ["jangan-bonus-buy-awal", "Jangan Bonus Buy di Awal", "tips bonus buy Nolimit"],
      ["main-singkat", "Main Singkat", "session singkat Nolimit"],
      ["kenali-theme-trigger", "Kenali Theme Trigger", "tips fitur Nolimit City"],
    ],
  },
  {
    id: "live",
    domain: "superdewa-live.com",
    accent: "site-accent-deepred",
    hero: "live.svg",
    topic: "Live Casino",
    name: "Live Casino Games Tutorial",
    nav: "Live Casino",
    pillarTitle: "Tutorial Live Casino Superdewa — Roulette, Baccarat, Blackjack",
    pillarH1: "Live casino tutorial: biar gak awkward pas pertama duduk di meja",
    pillarDek: "Dealer nyata, tempo cepat, etiket meja. Kita bongkar dasar-dasarnya biar kamu masuk dengan percaya diri.",
    keyword: "cara main live casino",
    about: "Tutorial edukasi live casino Superdewa: aturan dasar, etiket, dan kontrol session.",
    glossaries: [
      ["dealer-live", "Dealer Live", "dealer live casino"],
      ["betting-spot", "Betting Spot", "betting spot live casino"],
      ["roulette-european", "Roulette European", "roulette European"],
      ["roulette-american", "Roulette American", "roulette American"],
      ["baccarat-player-banker", "Player & Banker", "baccarat player banker"],
      ["blackjack-hit-stand", "Hit & Stand", "blackjack hit stand"],
      ["side-bet", "Side Bet", "side bet live casino"],
      ["game-show-live", "Game Show Live", "game show live casino"],
      ["payout-table", "Payout Table", "payout table live casino"],
      ["table-limit", "Table Limit", "table limit live casino"],
      ["speed-table", "Speed Table", "speed table live casino"],
      ["classic-table", "Classic Table", "classic table live casino"],
      ["commission", "Commission Baccarat", "commission baccarat"],
      ["insurance", "Insurance Blackjack", "insurance blackjack"],
      ["perfect-pair", "Perfect Pair", "perfect pair blackjack"],
      ["hot-cold-number", "Hot & Cold Number", "hot cold number roulette"],
      ["roadmaps-baccarat", "Roadmaps Baccarat", "roadmap baccarat"],
      ["shoe", "Shoe Kartu", "shoe kartu baccarat"],
      ["mobile-live", "Mobile Live", "live casino mobile"],
      ["latency", "Latency Live", "latency live casino"],
    ],
    guides: [
      ["cara-main-live-casino", "Cara Main Live Casino", "cara main live casino"],
      ["cara-main-roulette", "Cara Main Roulette", "cara main roulette"],
      ["cara-main-baccarat", "Cara Main Baccarat", "cara main baccarat"],
      ["cara-main-blackjack", "Cara Main Blackjack", "cara main blackjack"],
      ["cara-main-game-show", "Cara Main Game Show Live", "cara main game show live"],
      ["paham-table-limit", "Pahami Table Limit", "cara pilih table limit"],
      ["etiket-meja", "Etiket Meja Live", "etiket live casino"],
      ["tips-speed-table", "Tips Speed Table", "tips speed table"],
      ["manajemen-chip", "Manajemen Chip", "manajemen chip live casino"],
      ["baca-payout", "Cara Baca Payout", "cara baca payout live"],
      ["mobile-live-tips", "Tips Mobile Live", "tips live casino mobile"],
      ["mitos-roadmap", "Mitos Roadmap Baccarat", "mitos roadmap baccarat"],
      ["session-live-sehat", "Session Live Sehat", "session live casino sehat"],
      ["checklist-live", "Checklist Live Casino", "checklist live casino"],
    ],
    games: [
      ["roulette-inside-bets", "Roulette Inside Bets", "roulette inside bets"],
      ["roulette-outside-bets", "Roulette Outside Bets", "roulette outside bets"],
      ["baccarat-dasar", "Baccarat Dasar", "baccarat untuk pemula"],
      ["baccarat-side-bets", "Baccarat Side Bets", "baccarat side bets"],
      ["blackjack-dasar", "Blackjack Dasar", "blackjack untuk pemula"],
      ["blackjack-basic-strategy", "Basic Strategy Ringkas", "basic strategy blackjack"],
      ["crazy-game-show-style", "Game Show Style", "game show live casino"],
      ["dragon-tiger", "Dragon Tiger", "cara main dragon tiger"],
      ["sic-bo", "Sic Bo", "cara main sic bo"],
      ["poker-live", "Poker Live", "poker live casino"],
      ["andasan-vs-vip", "Meja Biasa vs VIP", "meja VIP live casino"],
      ["lightning-style", "Lightning Style Games", "lightning roulette style"],
    ],
    tips: [
      ["mulai-meja-low-limit", "Mulai Meja Low Limit", "tips meja low limit"],
      ["jangan-kejar-warna", "Jangan Kejar Warna", "tips roulette jangan kejar warna"],
      ["fokus-satu-game", "Fokus Satu Game", "tips fokus satu game live"],
      ["matikan-distraksi", "Matikan Distraksi", "tips fokus live casino"],
      ["set-timer-live", "Set Timer Live", "timer main live casino"],
      ["berhenti-saat-lelah", "Berhenti Saat Lelah", "tips berhenti live casino"],
    ],
  },
  {
    id: "crash",
    domain: "superdewa-crash.com",
    accent: "site-accent-lime",
    hero: "crash.svg",
    topic: "Crash Games",
    name: "Crash Games Guide",
    nav: "Crash",
    pillarTitle: "Panduan Crash Games Superdewa — Kurva, Cash Out & Mindset Risk",
    pillarH1: "Crash games guide: baca kurva, cash out, jaga kepala tetap dingin",
    pillarDek: "Multiplier naik, tekanan naik. Kita bahas mekanik generik crash + disiplin cash-out biar gak fomo buta.",
    keyword: "cara main crash game",
    about: "Panduan edukasi crash games Superdewa: kurva multiplier, cash-out, dan kontrol risiko.",
    glossaries: [
      ["multiplier-curve", "Multiplier Curve", "multiplier curve crash"],
      ["cash-out", "Cash Out", "cash out crash game"],
      ["auto-cash-out", "Auto Cash Out", "auto cash out crash"],
      ["crash-point", "Crash Point", "crash point artinya"],
      ["round-history", "Round History", "history crash game"],
      ["provably-fair-concept", "Provably Fair Concept", "provably fair crash"],
      ["bet-panel", "Bet Panel", "bet panel crash"],
      ["risk-curve", "Risk Curve", "risk curve crash"],
      ["martingale-myth", "Martingale Myth", "mitos martingale crash"],
      ["flat-betting", "Flat Betting", "flat betting crash"],
      ["session-bankroll", "Session Bankroll", "bankroll crash game"],
      ["volatility-crash", "Volatilitas Crash", "volatilitas crash game"],
      ["latency-cashout", "Latency Cash Out", "latency cash out"],
      ["mobile-crash", "Mobile Crash", "crash game mobile"],
      ["demo-crash", "Demo Crash", "demo crash game"],
      ["max-multiplier", "Max Multiplier", "max multiplier crash"],
      ["early-exit", "Early Exit", "early cash out"],
      ["late-exit", "Late Exit", "late cash out"],
      ["streak-bias", "Streak Bias", "streak bias crash"],
      ["house-edge-concept", "House Edge Concept", "house edge crash"],
    ],
    guides: [
      ["cara-main-crash-game", "Cara Main Crash Game", "cara main crash game"],
      ["cara-set-auto-cash-out", "Cara Set Auto Cash Out", "cara set auto cash out"],
      ["paham-kurva-multiplier", "Pahami Kurva Multiplier", "cara baca kurva crash"],
      ["manajemen-risk-crash", "Manajemen Risk Crash", "manajemen risiko crash"],
      ["flat-bet-strategy", "Flat Bet Strategy", "strategi flat bet crash"],
      ["mitos-pola-crash", "Mitos Pola Crash", "mitos pola crash game"],
      ["baca-history-bijak", "Baca History dengan Bijak", "cara baca history crash"],
      ["tips-mobile-crash", "Tips Mobile Crash", "tips crash game mobile"],
      ["session-timer-crash", "Session Timer Crash", "timer main crash"],
      ["jangan-martingale-buta", "Jangan Martingale Buta", "bahaya martingale crash"],
      ["demo-dulu-crash", "Demo Dulu Crash", "demo crash dulu"],
      ["bandingkan-crash-vs-slot", "Crash vs Slot", "crash vs slot"],
      ["psikologi-fomo", "Psikologi FOMO Crash", "FOMO crash game"],
      ["checklist-crash", "Checklist Crash Pemula", "checklist crash game"],
    ],
    games: [
      ["auto-vs-manual-cashout", "Auto vs Manual Cash Out", "auto vs manual cash out"],
      ["low-target-strategy", "Low Target Strategy", "strategi target rendah crash"],
      ["mid-target-strategy", "Mid Target Strategy", "strategi target menengah crash"],
      ["high-risk-target", "High Risk Target", "strategi target tinggi crash"],
      ["bankroll-persen", "Bankroll Persen", "persentase bankroll crash"],
      ["multi-bet-dasar", "Multi Bet Dasar", "multi bet crash"],
      ["grafik-history", "Grafik History", "grafik history crash"],
      ["fair-game-basics", "Fair Game Basics", "dasar fair crash game"],
      ["ui-crash-pemula", "UI Crash Pemula", "UI crash game pemula"],
      ["error-umum-pemula", "Error Umum Pemula", "kesalahan pemula crash"],
      ["cooldown-crash-cepat", "Cooldown Setelah Crash Cepat", "cooldown crash game"],
      ["responsible-crash", "Responsible Crash Play", "crash game bertanggung jawab"],
    ],
    tips: [
      ["target-kecil-konsisten", "Target Kecil Konsisten", "tips target kecil crash"],
      ["jangan-fomo", "Jangan FOMO", "tips anti FOMO crash"],
      ["cash-out-lebih-awal", "Cash Out Lebih Awal", "tips cash out awal"],
      ["limit-harian-crash", "Limit Harian Crash", "limit harian crash game"],
      ["jangan-main-marah", "Jangan Main Saat Marah", "tips emosi crash game"],
      ["catat-hasil-crash", "Catat Hasil Crash", "catat hasil crash game"],
    ],
  },
  {
    id: "sports",
    domain: "superdewa-sports.com",
    accent: "site-accent-field",
    hero: "sports.svg",
    topic: "Sportsbook",
    name: "Sportsbook Guide",
    nav: "Sportsbook",
    pillarTitle: "Panduan Sportsbook Superdewa — Odds, Handicap & Parlay",
    pillarH1: "Sportsbook guide: odds, handicap, parlay biar melek taruhan",
    pillarDek: "Bukan tipster palsu. Ini modul melek pasar: baca odds, pahami risiko parlay, jaga bankroll.",
    keyword: "panduan sportsbook",
    about: "Panduan edukasi sportsbook Superdewa: odds, pasar, dan disiplin taruhan olahraga.",
    glossaries: [
      ["odds-decimal", "Odds Decimal", "odds decimal artinya"],
      ["odds-american-ringkas", "Odds American Ringkas", "odds american artinya"],
      ["implied-probability", "Implied Probability", "implied probability odds"],
      ["handicap-asian", "Handicap Asian", "handicap asian artinya"],
      ["over-under", "Over Under", "over under artinya"],
      ["moneyline", "Moneyline", "moneyline artinya"],
      ["parlay", "Parlay", "parlay artinya"],
      ["live-betting", "Live Betting", "live betting artinya"],
      ["cash-out-sports", "Cash Out Sports", "cash out sportsbook"],
      ["early-payout", "Early Payout", "early payout sportsbook"],
      ["push", "Push", "push taruhan artinya"],
      ["void", "Void", "void bet artinya"],
      ["bankroll-sports", "Bankroll Sports", "bankroll sportsbook"],
      ["value-bet-concept", "Value Bet Concept", "value bet artinya"],
      ["juice-margin", "Juice / Margin", "juice bookmaker"],
      ["market-1x2", "Market 1X2", "pasar 1X2"],
      ["correct-score", "Correct Score", "correct score artinya"],
      ["half-time-full-time", "HT/FT", "half time full time"],
      ["player-prop", "Player Prop", "player prop bet"],
      ["settlement", "Settlement", "settlement taruhan"],
    ],
    guides: [
      ["cara-main-sportsbook", "Cara Main Sportsbook", "cara main sportsbook"],
      ["cara-baca-odds-decimal", "Cara Baca Odds Decimal", "cara baca odds decimal"],
      ["cara-main-handicap", "Cara Main Handicap", "cara main handicap asian"],
      ["cara-main-over-under", "Cara Main Over Under", "cara main over under"],
      ["cara-buat-parlay", "Cara Buat Parlay", "cara buat parlay"],
      ["paham-live-bet", "Pahami Live Bet", "cara live betting"],
      ["manajemen-bankroll-sports", "Manajemen Bankroll Sports", "manajemen bankroll sportsbook"],
      ["cari-value-sederhana", "Cari Value Sederhana", "cara cari value bet"],
      ["mitos-tipster", "Mitos Tipster", "mitos tipster bola"],
      ["baca-jadwal-pasar", "Baca Jadwal & Pasar", "cara baca pasar sportsbook"],
      ["mobile-sports-tips", "Tips Mobile Sports", "tips sportsbook mobile"],
      ["bandingkan-prematch-vs-live", "Prematch vs Live", "prematch vs live betting"],
      ["psikologi-chasing-loss", "Psikologi Chasing Loss", "chasing loss sportsbook"],
      ["checklist-sports", "Checklist Sportsbook", "checklist sportsbook"],
    ],
    games: [
      ["sepak-bola-dasar", "Sepak Bola Dasar", "taruhan sepak bola dasar"],
      ["basket-dasar", "Basket Dasar", "taruhan basket dasar"],
      ["tenis-dasar", "Tenis Dasar", "taruhan tenis dasar"],
      ["e-sports-dasar", "Esports Dasar", "taruhan esports dasar"],
      ["pasar-populer-bola", "Pasar Populer Bola", "pasar populer taruhan bola"],
      ["asian-handicap-contoh", "Contoh Asian Handicap", "contoh asian handicap"],
      ["over-under-contoh", "Contoh Over Under", "contoh over under"],
      ["parlay-risiko", "Risiko Parlay", "risiko parlay"],
      ["live-bet-disiplin", "Live Bet Disiplin", "disiplin live betting"],
      ["settlement-pahami", "Pahami Settlement", "cara kerja settlement"],
      ["statistik-yang-dicek", "Statistik yang Perlu Dicek", "statistik sebelum taruhan"],
      ["responsible-sports", "Responsible Sports Betting", "taruhan olahraga bertanggung jawab"],
    ],
    tips: [
      ["satu-pasar-dulu", "Satu Pasar Dulu", "tips pemula sportsbook"],
      ["unit-betting-kecil", "Unit Betting Kecil", "tips unit betting"],
      ["jangan-parlay-kebanyakan", "Jangan Parlay Kebanyakan", "tips parlay aman"],
      ["catat-tip", "Catat Tip & Hasil", "catat hasil taruhan"],
      ["istirahat-pasca-kalah", "Istirahat Pasca Kalah", "tips setelah kalah taruhan"],
      ["fokus-liga-dikenal", "Fokus Liga yang Dikenal", "tips pilih liga taruhan"],
    ],
  },
  {
    id: "play",
    domain: "superdewa-play.com",
    accent: "site-accent-calm",
    hero: "play.svg",
    topic: "Responsible Gambling",
    name: "Responsible Gambling Guide",
    nav: "Play Safe",
    pillarTitle: "Panduan Bermain Bertanggung Jawab Superdewa — Main Seru, Tetap Waras",
    pillarH1: "Main tetap seru, asal tetap waras — panduan bertanggung jawab",
    pillarDek: "Ini bukan kuliah membosankan. Ini toolkit biar hiburan tetap hiburan: batas waktu, batas uang, dan sinyal bahaya.",
    keyword: "bermain bertanggung jawab",
    about: "Panduan responsible gambling Superdewa: kontrol diri, batas sehat, dan dukungan edukatif.",
    glossaries: [
      ["limit-deposit", "Limit Deposit", "limit deposit artinya"],
      ["limit-waktu", "Limit Waktu", "limit waktu bermain"],
      ["self-exclusion", "Self Exclusion", "self exclusion artinya"],
      ["reality-check", "Reality Check", "reality check gambling"],
      ["bankroll", "Bankroll", "bankroll artinya"],
      ["tilt", "Tilt", "tilt artinya game"],
      ["chasing-losses", "Chasing Losses", "chasing losses artinya"],
      ["problem-gambling-signs", "Tanda Problem Gambling", "tanda problem gambling"],
      ["cooling-off", "Cooling Off", "cooling off period"],
      ["session-budget", "Session Budget", "session budget bermain"],
      ["entertainment-budget", "Entertainment Budget", "budget hiburan"],
      ["time-out", "Time Out", "time out bermain"],
      ["support-resources", "Support Resources", "bantuan problem gambling"],
      ["underage-prevention", "Underage Prevention", "pencegahan underage gambling"],
      ["healthy-habits", "Healthy Habits", "kebiasaan main sehat"],
      ["impulse-control", "Impulse Control", "kontrol impuls bermain"],
      ["transparency", "Transparency", "transparansi saat bermain"],
      ["fairness-concept", "Fairness Concept", "konsep permainan adil"],
      ["help-seeking", "Help Seeking", "mencari bantuan gambling"],
      ["recovery-basics", "Recovery Basics", "dasar pemulihan judi"],
    ],
    guides: [
      ["cara-set-batas-main", "Cara Set Batas Main", "cara set batas bermain"],
      ["cara-buat-budget-hiburan", "Cara Buat Budget Hiburan", "cara buat budget hiburan"],
      ["kenali-tanda-berbahaya", "Kenali Tanda Berbahaya", "tanda bahaya judi"],
      ["cara-istirahat-sehat", "Cara Istirahat Sehat", "cara istirahat dari game"],
      ["tip-hindari-tilt", "Tips Hindari Tilt", "cara hindari tilt"],
      ["cara-bicara-ke-teman", "Cara Bicara ke Teman", "cara bicara masalah judi"],
      ["digital-wellbeing-game", "Digital Wellbeing Game", "digital wellbeing bermain"],
      ["jadwal-main-seimbang", "Jadwal Main Seimbang", "jadwal bermain seimbang"],
      ["ganti-aktivitas", "Ganti Aktivitas", "alternatif selain judi"],
      ["pantau-emosi", "Pantau Emosi", "pantau emosi saat bermain"],
      ["checklist-sebelum-main", "Checklist Sebelum Main", "checklist sebelum bermain"],
      ["checklist-sesudah-main", "Checklist Sesudah Main", "checklist sesudah bermain"],
      ["panduan-keluarga-ringkas", "Panduan Keluarga Ringkas", "panduan keluarga judi"],
      ["langkah-minta-bantuan", "Langkah Minta Bantuan", "cara minta bantuan judi"],
    ],
    games: [
      ["mitos-menang-pasti", "Mitos Menang Pasti", "mitos menang pasti"],
      ["fomo-dan-iklan", "FOMO dan Iklan", "FOMO iklan judi"],
      ["sleep-dan-game", "Sleep dan Game", "tidur dan kebiasaan main"],
      ["uang-vs-hiburan", "Uang vs Hiburan", "uang versus hiburan"],
      ["sosial-pressure", "Tekanan Sosial", "tekanan sosial berjudi"],
      ["mobile-notification-trap", "Jebakan Notifikasi", "notifikasi aplikasi judi"],
      ["tracking-kebiasaan", "Tracking Kebiasaan", "lacak kebiasaan bermain"],
      ["tools-self-control", "Tools Self Control", "tools kontrol diri"],
      ["komunitas-sehat", "Komunitas Sehat", "komunitas bermain sehat"],
      ["cerita-refleksi", "Cerita Refleksi", "refleksi kebiasaan main"],
      ["batas-usia-18", "Batas Usia 18+", "batas usia 18 plus"],
      ["tautan-edukasi-superdewa", "Tautan Edukasi Superdewa", "edukasi Superdewa Group"],
    ],
    tips: [
      ["timer-wajib", "Timer Wajib", "tips timer bermain"],
      ["deposit-terpisah", "Deposit Terpisah", "tips budget terpisah"],
      ["jangan-pinjam", "Jangan Pinjam", "jangan pinjam untuk judi"],
      ["main-bareng-aturan", "Main dengan Aturan", "main dengan aturan sendiri"],
      ["rayakan-istirahat", "Rayakan Istirahat", "tips istirahat dari main"],
      ["ulangi-niat-awal", "Ulangi Niat Awal", "ingat niat awal bermain"],
    ],
  },
];
